events { worker_connections 1024; }

http {
    # Redirección de HTTP (80) a HTTPS (443)
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # Configuración de Servidor Seguro
    server {
        listen 443 ssl;
        server_name localhost;

        # Rutas donde Docker montará los certificados
        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        # Protocolo seguro requerido por el reto
        ssl_protocols TLSv1.3;

        location / {
            proxy_pass http://app-logic:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}